package com.bluemarlin.drinkdiary.ui.theme

import androidx.compose.ui.graphics.Color

val DrinkPaperLight = Color(0xFFFFF8F2)
val DrinkSurfaceLight = Color(0xFFFFFCF8)
val DrinkSurfaceVariantLight = Color(0xFFF4EAE1)
val DrinkOnSurfaceLight = Color(0xFF2C2723)
val DrinkOnSurfaceVariantLight = Color(0xFF655B53)
val DrinkOutlineLight = Color(0xFF8B8178)
val DrinkOutlineVariantLight = Color(0xFFD8CCC1)
val BottleGreenLight = Color(0xFF2F6F4E)
val BottleGreenContainerLight = Color(0xFFD8F0E0)
val MaltAmberLight = Color(0xFF9C6722)
val MaltAmberContainerLight = Color(0xFFFFE2B8)
val WineBerryLight = Color(0xFF93425E)
val WineBerryContainerLight = Color(0xFFFFD8E4)
val CorkErrorLight = Color(0xFFBA1A1A)

val CellarInkDark = Color(0xFF161211)
val CellarSurfaceDark = Color(0xFF211B19)
val CellarSurfaceVariantDark = Color(0xFF3B332F)
val CellarOnSurfaceDark = Color(0xFFF3ECE6)
val CellarOnSurfaceVariantDark = Color(0xFFD4C7BD)
val CellarOutlineDark = Color(0xFF9E9288)
val CellarOutlineVariantDark = Color(0xFF504741)
val BottleGreenDark = Color(0xFFA8D5BA)
val BottleGreenContainerDark = Color(0xFF1A5136)
val MaltAmberDark = Color(0xFFE7C46A)
val MaltAmberContainerDark = Color(0xFF5C3D0E)
val WineBerryDark = Color(0xFFEFB8C8)
val WineBerryContainerDark = Color(0xFF6F2A43)
val CorkErrorDark = Color(0xFFFFB4AB)

val ChartWineLight = Color(0xFFFF8FB3)
val ChartWhiskeyLight = Color(0xFFFFC66E)
val ChartBeerLight = Color(0xFF70D6FF)
val ChartWineDark = Color(0xFFFFB1C9)
val ChartWhiskeyDark = Color(0xFFFFD99A)
val ChartBeerDark = Color(0xFF9FE5FF)
